/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import java.awt.ScrollPane;
import java.awt.event.MouseEvent;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import modelo.Alumno;
import modelo.Lista_Doble;
import modelo.Nodo;

/**
 *
 * @author Delma
 */
public class frmAlumno extends javax.swing.JInternalFrame {

    /**
     * Creates new form Alumno
     */
    Lista_Doble ld = new Lista_Doble();
    DefaultTableModel model;

    public frmAlumno() {
        initComponents();
        this.setLocation(150, 40);
        this.setTitle("Mantenimiento de Alumnos");
        //ld.CargarAlumno();
        model = new DefaultTableModel();
        model.addColumn("CÓDIGO");
        model.addColumn("NOMBRES");
        model.addColumn("APELLIDOS");
        model.addColumn("DNI");
        model.addColumn("EDAD");
        model.addColumn("CELULAR");
        model.addColumn("ESTADO");
        tblAlumnos.setModel(model);
        ajustarColumnas();
        listar();
        deshabilitarTodo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        boxCodigo = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        boxEstado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();

        setClosable(true);
        setTitle("Mantenimiento de Alumnos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel1.setText("Codigo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel3.setText("Apellidos:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel4.setText("DNI:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel5.setText("Celular:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel6.setText("Estado:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        boxCodigo.setEnabled(false);
        boxCodigo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxCodigoItemStateChanged(evt);
            }
        });
        jPanel1.add(boxCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 110, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 196, -1));
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 196, -1));
        jPanel1.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 102, -1));
        jPanel1.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 102, -1));

        boxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrado", "Matriculado", "Retirado" }));
        boxEstado.setEnabled(false);
        jPanel1.add(boxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 102, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel7.setText("Edad:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 35, -1));

        btnAceptar.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 100, 40));

        btnCancelar.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 100, 40));

        btnEliminar.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 150, 50));

        btnModificar.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 150, 50));

        btnAdicionar.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setEnabled(false);
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 150, 50));

        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombres", "Apellidos", "DNI", "Edad", "Celular", "Estado"
            }
        ));
        tblAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlumnos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 670, 140));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 690, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        try {
            int codAlumno = leerCodigo();
            String nombre = leerNombres();
            if (nombre.length() != 0) {
                String apellidos = leerApellidos();
                if (apellidos.length() != 0) {
                    String dni = leerDNI();
                    try {
                        if (Integer.parseInt(dni) > 0 && Integer.parseInt(dni) < 100000000) {
                            try {
                                int edad = leerEdad();
                                try {
                                    int celular = leerCelular();
                                    int estado = leerEstado();
                                    if (estado != -1) {
                                        if (!btnAdicionar.isEnabled()) {
                                            if (!existeDNI(dni)) {
                                                Alumno nuevo = new Alumno(codAlumno, nombre, apellidos, 
                                                                            dni, edad, celular, estado);
                                                ld.insertarAlum(nuevo);
                                                ld.GuardarAlumnos();
                                                listar();
                                                mensaje("Nuevo alumno añadido exitosamente");
                                                deshabilitarTodo();
                                            } else {
                                                error("No puede ingresar un DNI ya existente", txtDNI);
                                            }
                                        } else if (!btnModificar.isEnabled()) {
                                            //Al darle en el alumno se cambiara 
                                            Alumno buscado = ld.buscarAlumno(codAlumno);
                                            buscado.setNombres(nombre);
                                            buscado.setApellidos(apellidos);
                                            buscado.setEdad(edad);
                                            buscado.setCelular(celular);
                                            ld.GuardarAlumnos();
                                            listar();
                                            mensaje("Alumno modificado exitosamente");
                                            deshabilitarTodo();
                                        }
                                    } else {
                                        error("Especifique el estado del alumno", boxEstado);
                                    }
                                } catch (Exception error) {
                                    error("Ingrese un número de celular válido", txtCelular);
                                }
                            } catch (Exception error) {
                                error("Ingrese una edad válida", txtEdad);
                            }
                        } else {
                            error("Ingrese un DNI válido", txtDNI);
                        }
                    } catch (Exception error) {
                        error("Ingrese un DNI válido", txtDNI);
                    }
                } else {
                    error("Ingrese los apellidos del alumno", txtApellidos);
                }
            } else {
                error("Ingrese el nombre del alumno", txtNombre);
            }
        } catch (Exception error) {
            error("Seleccione un código de alumno", boxCodigo);
        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        deshabilitarTodo();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        limpiar();
        habilitar(false, true, true, true, true, true, false, true, true, false, true, false);
        boxEstado.setSelectedIndex(0);
        boxCodigo.addItem(String.valueOf(ld.codigoCorrelativo()));
        boxCodigo.setSelectedIndex(ld.tamañoAlum());
        txtNombre.requestFocus();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (!btnAdicionar.isEnabled()) {
            deshabilitarTodo();
        }
        habilitar(true, true, true, false, true, true, false, true, true, true, false, false);
        boxCodigo.requestFocus();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            int codAlumno = leerCodigo();
            Alumno buscado = ld.buscarAlumno(codAlumno);
            if (buscado.getEstado() == 0) {
                ld.eliminarAlum(codAlumno);
                int fila = tblAlumnos.getSelectedRow();
                model.removeRow(fila);
                mensaje("Alumno eliminado exitosamente");
                deshabilitarTodo();

            } else {
                error("No puede eliminar a un alumno ya matriculado", boxCodigo);
            }
        } catch (Exception error) {
            error("Seleccione un código de alumno", boxCodigo);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlumnosMouseClicked
        if (btnAdicionar.isEnabled()) {
            try {
                Alumno buscado = ld.buscarAlumno(202010001 + tblAlumnos.getSelectedRow());
                boxCodigo.setSelectedIndex(tblAlumnos.getSelectedRow());
                txtNombre.setText(buscado.getNombres());
                txtApellidos.setText(buscado.getApellidos());
                txtDNI.setText(buscado.getDni());
                txtEdad.setText("" + buscado.getEdad());
                txtCelular.setText("" + buscado.getCelular());
                boxEstado.setSelectedIndex(buscado.getEstado());
            } catch (Exception error) {
            }
        }
    }//GEN-LAST:event_tblAlumnosMouseClicked

    private void boxCodigoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxCodigoItemStateChanged
        // TODO add your handling code here:
        try {
            int codAlumno = leerCodigo();
            Alumno buscado = ld.buscarAlumno(codAlumno);
            txtNombre.setText(buscado.getNombres());
            txtApellidos.setText(buscado.getApellidos());
            txtDNI.setText(buscado.getDni());
            txtEdad.setText("" + buscado.getEdad());
            txtCelular.setText("" + buscado.getCelular());
            boxEstado.setSelectedIndex(buscado.getEstado());
            tblAlumnos.setRowSelectionInterval(boxCodigo.getSelectedIndex(), boxCodigo.getSelectedIndex());
        } catch (Exception error) {

        }
    }//GEN-LAST:event_boxCodigoItemStateChanged

    int leerCodigo() {
        return Integer.parseInt(boxCodigo.getSelectedItem().toString());
    }

    String leerNombres() {
        return txtNombre.getText().trim().toUpperCase();
    }

    String leerApellidos() {
        return txtApellidos.getText().trim().toUpperCase();
    }

    String leerDNI() {
        return txtDNI.getText().trim().toUpperCase();
    }

    int leerEdad() {
        return Integer.parseInt(txtEdad.getText());
    }

    int leerCelular() {
        return Integer.parseInt(txtCelular.getText());
    }

    int leerEstado() {
        return boxEstado.getSelectedIndex();
    }

    boolean existeDNI(String dni) {
        return ld.ValidarDni(dni);
    }

    void listar() {
        model.getDataVector().removeAllElements();
        ld.Lista_Alumnos(model);
    }

    void mensaje(String s) {
        JOptionPane.showMessageDialog(this, s);
    }
    
    void habilitar(boolean codigo, boolean nombre, boolean apellidos, boolean dni, boolean edad, boolean celular,
            boolean estado, boolean aceptar, boolean cancelar, boolean adicionar, boolean modificar, boolean eliminar) {
        boxCodigo.setEnabled(codigo);
        txtNombre.setEditable(nombre);
        txtApellidos.setEditable(apellidos);
        txtDNI.setEditable(dni);
        txtEdad.setEditable(edad);
        txtCelular.setEditable(celular);
        boxEstado.setEnabled(estado);
        btnAceptar.setEnabled(aceptar);
        btnCancelar.setEnabled(cancelar);
        btnAdicionar.setEnabled(adicionar);
        btnModificar.setEnabled(modificar);
        btnEliminar.setEnabled(eliminar);
    }

    void deshabilitarTodo() {
        listarCboCodigo();
        habilitar(false, false, false, false, false, false, false, false, false, true, true, true);
        limpiar();
    }

    void limpiar() {
        boxCodigo.setSelectedIndex(-1);
        txtNombre.setText("");
        txtApellidos.setText("");
        txtDNI.setText("");
        txtEdad.setText("");
        txtCelular.setText("");
        boxEstado.setSelectedIndex(-1);
    }

    void listarCboCodigo() {
        boxCodigo.removeAllItems();

        ld.cajaAlum(boxCodigo);
    }

    void error(String s, JComboBox cbo) {
        JOptionPane.showMessageDialog(this, s, "", JOptionPane.ERROR_MESSAGE);
        cbo.requestFocus();
    }

    void error(String s, JTextField txt) {
        JOptionPane.showMessageDialog(this, s, "", JOptionPane.ERROR_MESSAGE);
        txt.selectAll();
        txt.requestFocus();
    }

    void ajustarColumnas() {
        TableColumnModel modeloColuma = tblAlumnos.getColumnModel();
        modeloColuma.getColumn(0).setPreferredWidth(jScrollPane1.getWidth()*2);
        modeloColuma.getColumn(1).setPreferredWidth(jScrollPane1.getWidth()*4);
        modeloColuma.getColumn(2).setPreferredWidth(jScrollPane1.getWidth()*4);
        modeloColuma.getColumn(3).setPreferredWidth(jScrollPane1.getWidth()*2);
        modeloColuma.getColumn(4).setPreferredWidth(jScrollPane1.getWidth()*1);
        modeloColuma.getColumn(5).setPreferredWidth(jScrollPane1.getWidth()*2);
        modeloColuma.getColumn(6).setPreferredWidth(jScrollPane1.getWidth()*3);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCodigo;
    private javax.swing.JComboBox<String> boxEstado;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAlumnos;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
