/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import modelo.Estudiante;
import modelo.Curso;
import modelo.Lista_Doble;
import modelo.Matricula;

/**
 *
 * @author acer
 */
public class frmConEstudiante extends javax.swing.JInternalFrame {

    Lista_Doble ld = new Lista_Doble();

    /**
     * Creates new form frmConAlumno
     */
    public frmConEstudiante() {
        initComponents();
        this.setLocation(150, 40);
        ld.CargarEstudiante();
        ld.CargarCurso();
        ld.CargarMatricula();
        ld.CargarRetiro();
        listarCboCodigo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        boxCod = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btnConsultar = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Codigo de Estudiante:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        boxCod.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        boxCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxCodActionPerformed(evt);
            }
        });
        jPanel1.add(boxCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 120, -1));

        txtResultado.setColumns(20);
        txtResultado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 470, 240));

        btnConsultar.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/search.png"))); // NOI18N
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        try {
            txtResultado.setText("");
            listar();
            boxCod.requestFocus();
        } catch (Exception error) {
            mensaje("Seleccione un código de alumno");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void boxCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxCodActionPerformed

    }//GEN-LAST:event_boxCodActionPerformed

    void imprimir() {
        imprimir("");
    }

    //metodo Listar
    void listar() {
        Estudiante x = ld.buscarEstudiante(leerCodigo());
        imprimir("CÓDIGO               : " + x.getCodEstudiante());
        imprimir("NOMBRES              : " + x.getNombres());
        imprimir("APELLIDOS            : " + x.getApellidos());
        imprimir("DNI                  : " + x.getDni());
        imprimir("EDAD                 : " + x.getEdad());
        imprimir("CELULAR              : " + x.getCelular());
        imprimir("ESTADO               : " + nombreEstado(x.getEstado()));
        imprimir();
        if (x.getEstado() != 0) {
            
            Matricula m = ld.buscarMatriculaxAlum(leerCodigo());
            Curso c = ld.buscarCurso(m.getCodigoCurso());
            imprimir("ASIGNATURA           : " + c.getAsignatura());
            imprimir("CICLO                : " + nombreCiclo(c.getCiclo()));
            imprimir("CANTIDAD DE CRÉDITOS : " + c.getCreditos());
            imprimir("HORAS                : " + c.getHoras());
            
        }
    }

    void listarCboCodigo() {
        boxCod.removeAllItems();
        ld.cajaEstu(boxCod);
        boxCod.setSelectedIndex(-1);
    }

    String nombreEstado(int i) {
        switch (i) {
            case 0:
                return "REGISTRADO";
            case 1:
                return "MATRICULADO";
            case 2:
                return "RETIRADO";
            default:
                return null;
        }
    }

public String nombreCiclo(int i) {
        switch (i) {
            case 0:
                return "PRIMERO";
            case 1:
                return "SEGUNDO";
            case 2:
                return "TERCERO";
            case 3:
                return "CUARTO";
            case 4:
                return "QUINTO";
            case 5:
                return "SEXTO";
            case 6:
                return "SEPTIMO";
            case 7:
                return "OCTAVO";
            case 8:
                return "NOVENO";
            case 9:
                return "DECIMO";
            default:
                return null;
        }
    }


    void imprimir(String s) {
        txtResultado.append(s + "\n");
    }

    void mensaje(String s) {
        JOptionPane.showMessageDialog(this, s);
    }

    public int leerCodigo() {
        return Integer.parseInt(boxCod.getSelectedItem().toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCod;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
