/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author acer
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Inicio");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnIncio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        MnArchivo = new javax.swing.JMenu();
        MnSalir = new javax.swing.JMenuItem();
        MnMantenimiento = new javax.swing.JMenu();
        MnEstudiante = new javax.swing.JMenuItem();
        MnProfesor = new javax.swing.JMenuItem();
        MnCurso = new javax.swing.JMenuItem();
        MnRegistro = new javax.swing.JMenu();
        MnMatricula = new javax.swing.JMenuItem();
        MnRetiro = new javax.swing.JMenuItem();
        MnConsulta = new javax.swing.JMenu();
        MnConEstudiante = new javax.swing.JMenuItem();
        MnConProfesor = new javax.swing.JMenuItem();
        MnConCurso = new javax.swing.JMenuItem();
        MnConMatricula = new javax.swing.JMenuItem();
        MnConRetiro = new javax.swing.JMenuItem();
        MnReporte = new javax.swing.JMenu();
        MnEstuPen = new javax.swing.JMenuItem();
        MnEstuVigen = new javax.swing.JMenuItem();
        MnEstuRet = new javax.swing.JMenuItem();
        MnEstuCur = new javax.swing.JMenuItem();
        MnEstuProf = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        pnIncio.setPreferredSize(new java.awt.Dimension(800, 475));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/unt.png"))); // NOI18N

        pnIncio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnIncioLayout = new javax.swing.GroupLayout(pnIncio);
        pnIncio.setLayout(pnIncioLayout);
        pnIncioLayout.setHorizontalGroup(
            pnIncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 993, Short.MAX_VALUE)
        );
        pnIncioLayout.setVerticalGroup(
            pnIncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MnArchivo.setText("X");
        MnArchivo.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N

        MnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MnSalir.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        MnSalir.setText("X");
        MnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnSalirActionPerformed(evt);
            }
        });
        MnArchivo.add(MnSalir);

        jMenuBar2.add(MnArchivo);

        MnMantenimiento.setText("Gestión");
        MnMantenimiento.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N

        MnEstudiante.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        MnEstudiante.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        MnEstudiante.setText("Estudiante");
        MnEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnEstudianteActionPerformed(evt);
            }
        });
        MnMantenimiento.add(MnEstudiante);

        MnProfesor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        MnProfesor.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        MnProfesor.setText("Profesor");
        MnProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnProfesorActionPerformed(evt);
            }
        });
        MnMantenimiento.add(MnProfesor);

        MnCurso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        MnCurso.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        MnCurso.setText("Curso");
        MnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCursoActionPerformed(evt);
            }
        });
        MnMantenimiento.add(MnCurso);

        jMenuBar2.add(MnMantenimiento);

        MnRegistro.setText("Registro");
        MnRegistro.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N

        MnMatricula.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        MnMatricula.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        MnMatricula.setText("Matricula");
        MnMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnMatriculaActionPerformed(evt);
            }
        });
        MnRegistro.add(MnMatricula);

        MnRetiro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        MnRetiro.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        MnRetiro.setText("Retiro");
        MnRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRetiroActionPerformed(evt);
            }
        });
        MnRegistro.add(MnRetiro);

        jMenuBar2.add(MnRegistro);

        MnConsulta.setText("Busqueda");
        MnConsulta.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N

        MnConEstudiante.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MnConEstudiante.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        MnConEstudiante.setText("Estudiante");
        MnConEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnConEstudianteActionPerformed(evt);
            }
        });
        MnConsulta.add(MnConEstudiante);

        MnConProfesor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MnConProfesor.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        MnConProfesor.setText("Profesor");
        MnConProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnConProfesorActionPerformed(evt);
            }
        });
        MnConsulta.add(MnConProfesor);

        MnConCurso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MnConCurso.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        MnConCurso.setText("Curso");
        MnConCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnConCursoActionPerformed(evt);
            }
        });
        MnConsulta.add(MnConCurso);

        MnConMatricula.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MnConMatricula.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        MnConMatricula.setText("Matricula");
        MnConMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnConMatriculaActionPerformed(evt);
            }
        });
        MnConsulta.add(MnConMatricula);

        MnConRetiro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MnConRetiro.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        MnConRetiro.setText("Retiro");
        MnConRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnConRetiroActionPerformed(evt);
            }
        });
        MnConsulta.add(MnConRetiro);

        jMenuBar2.add(MnConsulta);

        MnReporte.setText("Reporte");
        MnReporte.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N

        MnEstuPen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        MnEstuPen.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        MnEstuPen.setText("Estudiantes con matricula pendiente");
        MnEstuPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnEstuPenActionPerformed(evt);
            }
        });
        MnReporte.add(MnEstuPen);

        MnEstuVigen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        MnEstuVigen.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        MnEstuVigen.setText("Estudiante con matricula vigente");
        MnEstuVigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnEstuVigenActionPerformed(evt);
            }
        });
        MnReporte.add(MnEstuVigen);

        MnEstuRet.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        MnEstuRet.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        MnEstuRet.setText("Estudiantes retirados");
        MnEstuRet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnEstuRetActionPerformed(evt);
            }
        });
        MnReporte.add(MnEstuRet);

        MnEstuCur.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        MnEstuCur.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        MnEstuCur.setText("Estudiantes matriculados por curso");
        MnEstuCur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnEstuCurActionPerformed(evt);
            }
        });
        MnReporte.add(MnEstuCur);

        MnEstuProf.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        MnEstuProf.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        MnEstuProf.setText("Estudiantes matriculados por profesor");
        MnEstuProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnEstuProfActionPerformed(evt);
            }
        });
        MnReporte.add(MnEstuProf);

        jMenuBar2.add(MnReporte);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnIncio, javax.swing.GroupLayout.PREFERRED_SIZE, 993, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnIncio, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MnSalirActionPerformed

    private void MnEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnEstudianteActionPerformed
        frmEstudiante ventana = new frmEstudiante();
        pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnEstudianteActionPerformed

    private void MnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCursoActionPerformed
        frmCurso ventana = new frmCurso();
        pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnCursoActionPerformed

    private void MnMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnMatriculaActionPerformed
        frmMatricula ventana = new frmMatricula();
        pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnMatriculaActionPerformed

    private void MnRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRetiroActionPerformed
        frmRetiro ventana = new frmRetiro();
        pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnRetiroActionPerformed

    private void MnEstuPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnEstuPenActionPerformed
        frmMatriculaPendiente ventana = new frmMatriculaPendiente();
        pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnEstuPenActionPerformed

    private void MnEstuVigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnEstuVigenActionPerformed
        frmMatriculaVigente ventana = new frmMatriculaVigente();
        pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnEstuVigenActionPerformed

    private void MnEstuCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnEstuCurActionPerformed
        frmMatriculadosCurso ventana = new frmMatriculadosCurso();
        pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnEstuCurActionPerformed

    private void MnConRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnConRetiroActionPerformed
        frmConRetiro ventana = new frmConRetiro();
        pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnConRetiroActionPerformed

    private void MnConMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnConMatriculaActionPerformed
        frmConMatricula ventana = new frmConMatricula();
        pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnConMatriculaActionPerformed

    private void MnConCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnConCursoActionPerformed
        frmConCurso ventana = new frmConCurso();
        pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnConCursoActionPerformed

    private void MnConEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnConEstudianteActionPerformed
        frmConEstudiante ventana = new frmConEstudiante();
        pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnConEstudianteActionPerformed

    private void MnConProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnConProfesorActionPerformed
        frmConProfesor ventana = new frmConProfesor();
        pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnConProfesorActionPerformed

    private void MnEstuProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnEstuProfActionPerformed
        frmMatriculadosProfesor ventana = new frmMatriculadosProfesor();
        pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnEstuProfActionPerformed

    private void MnEstuRetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnEstuRetActionPerformed
        frmMatriculaRetirada ventana = new frmMatriculaRetirada();
        pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnEstuRetActionPerformed

    private void MnProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnProfesorActionPerformed
        frmProfesor ventana = new frmProfesor();
        pnIncio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MnProfesorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu MnArchivo;
    private javax.swing.JMenuItem MnConCurso;
    private javax.swing.JMenuItem MnConEstudiante;
    private javax.swing.JMenuItem MnConMatricula;
    private javax.swing.JMenuItem MnConProfesor;
    private javax.swing.JMenuItem MnConRetiro;
    public javax.swing.JMenu MnConsulta;
    private javax.swing.JMenuItem MnCurso;
    private javax.swing.JMenuItem MnEstuCur;
    private javax.swing.JMenuItem MnEstuPen;
    private javax.swing.JMenuItem MnEstuProf;
    private javax.swing.JMenuItem MnEstuRet;
    private javax.swing.JMenuItem MnEstuVigen;
    private javax.swing.JMenuItem MnEstudiante;
    public javax.swing.JMenu MnMantenimiento;
    private javax.swing.JMenuItem MnMatricula;
    private javax.swing.JMenuItem MnProfesor;
    public javax.swing.JMenu MnRegistro;
    public javax.swing.JMenu MnReporte;
    private javax.swing.JMenuItem MnRetiro;
    private javax.swing.JMenuItem MnSalir;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JMenuBar jMenuBar2;
    public javax.swing.JDesktopPane pnIncio;
    // End of variables declaration//GEN-END:variables
}
